### ISSUE TITLE
Se necesita una funcion que chequee si un array tiene elementos duplicados

### ISSUE THREAD

**Issue by gquiroz-oneloop** [francasas/iniciodev#18]
function hasDuplicatedValues(array) {

}

Por ejemplo 
var array1 = [ 2, 3, 4, 7, 7, 31] Deberia devolver true

var array1 = [ 2, 3, 4, 7, 2, 31] Deberia devolver false

**Comment by francasas** [comment]
function hasDuplicatedValues(value1,value2) {
    var result=[]
    for (i = 0; i < value1.Length; i++) {
        for (j = 0; j < value2Length; j++) {
          if (a[i] == a[j] && i != j && !result.contains(a[i])) {
            result.push(a[i]);
          }
        }
      }
      return result;
};
