### ISSUE TITLE
Se debera crear una funcion que en base a dos parametros devuelva un array con esos elementos

### ISSUE THREAD

**Issue by gquiroz-oneloop** [francasas/iniciodev#3]
### Firma del metodo
function joinElements(firstValue,secondValue) {
}

### Tiene que recibir 
14 y 22

### Tiene que devolver 
[14,22];

**Comment by francasas** [comment]
no se llega a resultado ya que no es posible lograr la comparacion.
deberiamos hacer un straight y de todas maneras no llegariamos a lo que se requiere
